# -*- coding: utf-8 -*-
"""ep4_6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1grtsv15O963lRyW7Em-ZGlaERWVoPbPi
"""

#Declarando a variável

n = int(input())


#Configurando o método do cálculo do somatório 1

def calculando_somatorio_i(n):
  r = 0
  for i in range(1,n+1):
    for j in range(1,8+1):

      r += (i + 1) * j
  print(r)

#Definindo a saída do programa:

calculando_somatorio_i(n)